
internal_links = {'abstract': ('%s://wwwin-pyats.cisco.com/cisco-shared/abstract/html/', '%s'),
                  'apis': ('%s://wwwin-pyats.cisco.com/cisco-shared/genie/latest/genie_libs/#/apis', '%s'),
                  'parsergen': ('%s://wwwin-pyats.cisco.com/cisco-shared/parsergen/latest/index.html', '%s'),
                  'metaparser': ('%s://wwwin-pyats.cisco.com/cisco-shared/metaparser/latest/', '%s'),
                  'predcore': ('%s://wwwin-pyats.cisco.com/cisco-shared/predcore/latest/', '%s'),
                  'pyats': ('%s://wwwin-pyats.cisco.com', '%s'),
                  'abstractiontokens': ('%s://wwwin-pyats.cisco.com/cisco-shared/abstract/html/concept.html#abstraction-tokens', '%s'),
                  'genielibs_repo': ('%ss://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse', '%s'),
                  'parser_repo': ('%s://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genieparser/browse', '%s'),
                  'filetransferlibs_repo': ('%s://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/geniefiletransferutilslib/browse', '%s'),
                  'telemetry_repo': ('%s://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genietelemetry/browse', '%s'),
                  'connectionpool': ('%s://wwwin-pyats.cisco.com/documentation/latest/connections/manager.html#method-start-pool', '%s'),
                  'connectdevice': ('%s://wwwin-pyats.cisco.com/documentation/latest/connections/manager.html#method-connect', '%s'),
                  'coding':('%s://wiki.cisco.com/display/GENIE/Coding+Guidelines', '%s'),
                  'commit':('%ss://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/COMMIT.md', '%s'),
                  'ops':('%ss://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/OPS.md', '%s'),
                  'conf':('%ss://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/CONF.md', '%s'),
                  'permission':('%s://wiki.cisco.com/display/PYATS/Bitbucket+Repo#BitbucketRepo-BitbucketMembership', '%s'),
                  'mailto': ('mailto:asg-genie-support@%s', '%s'),
                  'setuptools':('%s://setuptools.readthedocs.io/en/latest/setuptools.html#develop-deploy-the-project-source-in-development-mode', '%s'),
                  'connection-pool':('%s://wwwin-pyats.cisco.com/documentation/latest/connections/sharing.html#connection-pools', '%s'),
                  'lookupdecorator':('%s://wwwin-pyats.cisco.com/cisco-shared/abstract/html/lookup_decorator.html', '%s'),
                  'models': ('%s://wwwin-pyats.cisco.com/cisco-shared/genie/latest/genie_libs/#/models', '%s'),
                  'triggers': ('%s://wwwin-pyats.cisco.com/cisco-shared/genie/latest/genie_libs/#/triggers', '%s'),
                  'parsers': ('%s://wwwin-pyats.cisco.com/cisco-shared/genie/latest/genie_libs/#/parsers', '%s'),
                  'verifications': ('%s://wwwin-pyats.cisco.com/cisco-shared/genie/latest/genie_libs/#/verifications', '%s'),
                  'robot': ('%s://wwwin-pyats.cisco.com/cisco-shared/genie/latest/robot.html', '%s'),
                  'robotframework': ('%s://robotframework.org/', '%s'),
                  'lookupclass':('%s://wwwin-pyats.cisco.com/cisco-shared/abstract/html/lookup_class.html', '%s'),
                  'abstract_topology':('%s://wwwin-pyats.cisco.com/cisco-shared/abstract/latest/lookup_class.html#integration-with-topology', '%s'),
                  'best':('%s://wwwin-best.cisco.com/', '%s'),
                  'testbed':('%s://wwwin-pyats.cisco.com/documentation/latest/topology/index.html', '%s'),
                  'steps':('%s://wwwin-pyats.cisco.com/documentation/latest/aetest/steps.html', '%s'),
                  'easypy':('%s://wwwin-pyats.cisco.com/documentation/latest/easypy/usages.html#standard-arguments', '%s'),
                  'aetest':('%s://wwwin-pyats.cisco.com/documentation/latest/aetest/run.html?highlight=uids#standard-arguments', '%s'),
                  'jobfile':('%s://wwwin-pyats.cisco.com/documentation/latest/easypy/jobfile.html', '%s'),
                  'logic':('%s://wwwin-pyats.cisco.com/documentation/latest/datastructures/logic.html#logic-from-str', '%s'),
                  'processors': ('%s://wwwin-pyats.cisco.com/documentation/latest/aetest/processors.html', '%s'),
                  'ydk':('%s://github.com/CiscoDevNet/ydk-gen/', '%s'),
                  'connection':('%s://wwwin-pyats.cisco.com/documentation/latest/connections/integration.html', '%s'),
                  'unicon_recording':('%s://wwwin-pyats.cisco.com/cisco-shared/unicon/latest/playback/index.html#record', '%s'),
                  'unicon_replay':('%s://wwwin-pyats.cisco.com/cisco-shared/unicon/latest/playback/index.html#replay', '%s'),
                  'unicon_playback':('%s://wwwin-pyats.cisco.com/cisco-shared/unicon/latest/playback/index.html#playback', '%s'),
                  'pyats_topology':('%s://wwwin-pyats.cisco.com/documentation/html/topology/index.html', '%s'),
                  'pyats_interface':('%s://wwwin-pyats.cisco.com/documentation/latest/topology/concept.html#interface-objects', '%s'),
                  'pyats_link':('%s://wwwin-pyats.cisco.com/documentation/latest/topology/concept.html#link-objects', '%s'),
                  'pyats_device':('%s://wwwin-pyats.cisco.com/documentation/latest/topology/concept.html#device-objects', '%s'),
                  'pyats_gettingstarted':('%s://wwwin-pyats.cisco.com/documentation/latest/getting_started/index.html#installation', '%s'),
                  'pyats_settestbed':('%s://wwwin-pyats.cisco.com/documentation/latest/getting_started/index.html#describe-your-testbed', '%s'),
                  'pyats_secret_string':('%s://wwwin-pyats.cisco.com/documentation/latest/utilities/secret_strings.html#secret-strings', '%s'),
                  'genietelemetry':('%s://wwwin-pyats.cisco.com/cisco-shared/genietelemetry/html/', '%s'),
                  'genietrafficgen':('%s://wwwin-pyats.cisco.com/cisco-shared/genietrafficgen/html/', '%s'),
                  'subsections':('%s://wwwin-pyats.cisco.com/documentation/latest/aetest/structure.html#subsections', '%s'),
                  'filetransferutils_examples':('%s://wwwin-pyats.cisco.com/cisco-shared/filetransferutils/latest/introduction.html#example', '%s'),
                  'pyats_rollup':('%s://wwwin-pyats.cisco.com/documentation/latest/results/rollup.html', '%s'),
                  'filetransferutils':('%s://wwwin-pyats.cisco.com/cisco-shared/filetransferutils/latest/introduction.html', '%s'),
                  'geniewiki':('%s://wiki.cisco.com/display/GENIE/Genie+Guidelines', '%s'),
                  'pyatswiki':('%s://wiki.cisco.com/pages/viewpage.action?pageId=80375302', '%s'),
                  'testcase':('%s://wwwin-pyats.cisco.com/cisco-shared/genie/latest/genie_libs/#/triggers', '%s'),
                  'virl':('%s://getvirl.cisco.com/downloads.php', '%s'),
                  'windows':('%s://getvirl.cisco.com/player.php', '%s'),
                  'mac':('%s://getvirl.cisco.com/fusion.php', '%s'),
                  'vsphere':('%s://getvirl.cisco.com/vs.web.php', '%s'),
                  'virl_tutorials':('%s://virl-dev-innovate.cisco.com/tutorials.php', '%s'),
                  'cisco_virl':('%s://www.youtube.com/channel/UC41WuzXlJCGY5qLsuZ8aHkQ', '%s'),
                  'genielibsgitclone':('git@wwwin-github.cisco.com:pyATS/genielibs%s', '%s'),
                  'genieparsergitclone':('git@wwwin-github.cisco.com:pyATS/genieparser%s', '%s'),
                  'pyats_robot':('%s://wwwin-pyats.cisco.com/documentation/latest/robot/index.html', '%s'),
                  'devnet':('%ss://developer.cisco.com/site/pyats/', '%s'),
                  'internal_devnet':('%ss://wiki.cisco.com/display/PYATS/DevNet', '%s'),
                  'pyats_find':('%s://wwwin-pyats.cisco.com/documentation/latest/utilities/helper_functions.html#find', '%s'),
                  'reserve':('%ss://github.com/CiscoDevNet/pyats-labs/blob/master/labs/intro-to-genie/1.md#prerequisites', '%s'),
                  'launch':('%ss://github.com/CiscoDevNet/pyats-labs/blob/master/labs/intro-to-genie/2.md#step-2-launch-genie-virl-simulation', '%s'),
                  'pickle':('%ss://docs.python.org/3.5/library/pickle.html', '%s'),
                  'regex':('%ss://docs.python.org/3.5/library/re.html', '%s'),
                  'ixiasupport':('%ss://support.ixiacom.com/support-overview/product-support/downloads-updates/versions/68', '%s'),
                  'ixnetwork_pypi':('%ss://pypi.org/project/ixnetwork/', '%s'),
                  'atsinstall':('%s://wwwin-ats.cisco.com/release_notes/5.3.0/ATS5.3.0.htm', '%s'),
                  'atsc3':('%ss://wiki.cisco.com/display/ATS/ATS-5.3.0-Component-Release-C3#ATS-5.3.0-Component-Release-C3-TarBallTreeUpgradeProcess', '%s'),
                  'sdkchangelog':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/sdk-pkg/changelog/2018/%s.md', '%s'),
                  'parserchangelog':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genieparser/browse/changelog/2018/%s.md', '%s'),
                  'confchangelog':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/conf-pkg/changelog/2018/%s.md', '%s'),
                  'opschangelog':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/ops-pkg/changelog/2018/%s.md', '%s'),
                  'robotchangelog':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/robot-pkg/changelog/2018/%s.md', '%s'),
                  'sdkchangelog19':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/sdk-pkg/changelog/2019/%s.md', '%s'),
                  'parserchangelog19':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genieparser/browse/changelog/2019/%s.md', '%s'),
                  'confchangelog19':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/conf-pkg/changelog/2019/%s.md', '%s'),
                  'opschangelog19':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/ops-pkg/changelog/2019/%s.md', '%s'),
                  'robotchangelog19':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/robot-pkg/changelog/2019/%s.md', '%s'),
                  'sdkchangelog20':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/sdk-pkg/changelog/2020/%s.md', '%s'),
                  'parserchangelog20':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genieparser/browse/changelog/2020/%s.md', '%s'),
                  'cleanchangelog20':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/clean-pkg/changelog/2020/%s.md', '%s'),
                  'confchangelog20':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/conf-pkg/changelog/2020/%s.md', '%s'),
                  'opschangelog20':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/ops-pkg/changelog/2020/%s.md', '%s'),
                  'robotchangelog20':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genielibs/browse/pkgs/robot-pkg/changelog/2020/%s.md', '%s'),
                  'trafficgenchangelog20':('https://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genietrafficgen/browse/docs/changelog/2020%s.rst', '%s'),
                  'genie_training_kata':('%ss://www.katacoda.com/jeaubin/scenarios/install', '%s'),
                  'genie_workshop':('%ss://github.com/CiscoTestAutomation/CL-DevNet-2595', '%s'),
                  'pyats_genie_workshop':('%ss://github.com/RunSi/DEVWKS-2601', '%s'),
                  'genie_command_line': ('%s://wwwin-pyats.cisco.com/cisco-shared/genie/latest/cli/index.html', '%s'),
                  'genie_traffic_gen': ('%s://wwwin-pyats.cisco.com/cisco-shared/genietrafficgen/html/', '%s'),
                  'genie_bootcamp': ('%ss://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genie-bootcamp/browse', '%s'),
                  'classtutorial': ('%s://docs.python.org/3/tutorial/classes.html', '%s'),
                  'wikipedia': ('%s://en.wikipedia.org/wiki/Abstraction_(software_engineering)', '%s'),
                  'dynamicallytyped': ('%s://en.wikipedia.org/wiki/Type_system#Dynamic_type_checking_and_runtime_type_information', '%s'),
                  'ducktyping': ('%s://en.wikipedia.org/wiki/Duck_typing', '%s'),
                  'inheritance': ('%s://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)', '%s'),
                  'objectoriented': ('%s://en.wikipedia.org/wiki/Object-oriented_programming', '%s'),
                  'FactoryMethods': ('%s://en.wikipedia.org/wiki/Factory_(object-oriented_programming)', '%s'),
                  'pythonmodules': ('%s://docs.python.org/3/tutorial/modules.html#packages', '%s'),
                  'pythonpackages': ('%s://docs.python.org/3/tutorial/modules.html', '%s'),
                  'pythonimportsystem': ('%s://docs.python.org/3/reference/import.html', '%s'),
                  'modulenamingconvention': ('%s://www.python.org/dev/peps/pep-0008/#package-and-module-names', '%s'),
                  'codereview': ('%s://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genieparser/pull-requests?create', '%s'),
                  'staticscope': ('%s://docs.python.org/3/whatsnew/2.1.html', '%s'),
                  'inheritancetutorial': ('%s://docs.python.org/2/tutorial/classes.html?highlight=inheritance', '%s'),
                  'parsergenworkshop': ('%s://github.com/RunSi/DEVWKS-2601', '%s'),
                  'vod': ('%s://cisco.webex.com/ciscosales/ldr.php?RCID=b963a0319429876a8b332bf9b0962a1f', '%s'),
                  'communityforum': ('%s://piestack.cisco.com', '%s'),
                  'blitz': ('%s://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writetrigger/writetrigger.html', '%s'),
                  'ListDict': ('%s://pubhub.devnetcloud.com/media/pyats/docs/datastructures/listdict.html', '%s'),
                  }

external_links = {'abstract': ('%ss://pubhub.devnetcloud.com/media/genie-abstraction/docs/index.html', 'abstract'),
                  'apis': ('%ss://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/apis','apis'),
                  'parsergen': ('%ss://pubhub.devnetcloud.com/media/genie-parsergen/docs/index.html', 'parsergen'),
                  'metaparser': ('%ss://pubhub.devnetcloud.com/media/genie-metaparser/docs/index.html', 'metaparser'),
                  'predcore': ('%ss://pubhub.devnetcloud.com/media/genie-predcore/docs/index.html', 'predcore'),
                  'pyats': ('%ss://developer.cisco.com/site/pyats/', 'pyATS'),
                  'abstractiontokens': ('%ss://pubhub.devnetcloud.com/media/genie-abstraction/docs/concept.html#abstraction-tokens', 'abstractiontokens'),
                  'parser_repo': ('%ss://github.com/CiscoTestAutomation/genieparser', 'parser source'),
                  'filetransferlibs_repo': ('%ss://github.com/CiscoTestAutomation/geniefiletransferutilslib', 'filetransferlibs_repo'),
                  'genielibs_repo': ('%ss://github.com/CiscoTestAutomation/genielibs', 'telemetry source'),
                  'telemetry_repo': ('%ss://github.com/CiscoTestAutomation/genietelemetrylibs', 'telemetry source'),
                  'connectionpool' : ("%ss://pubhub.devnetcloud.com/media/pyats/docs/connections/manager.html#method-start-pool","connectionpool"),
                  'connectdevice' : ("%ss://pubhub.devnetcloud.com/media/pyats/docs/connections/manager.html#method-connect","connectdevice"),
                  'coding': ('',''),
                  'commit':('%ss://github.com/CiscoTestAutomation/genielibs/blob/master/COMMIT.md','commit'),
                  'ops':('%ss://github.com/CiscoTestAutomation/genielibs/blob/master/OPS.md','ops'),
                  'conf':('%ss://github.com/CiscoTestAutomation/genielibs/blob/master/CONF.md','conf'),
                  'permission': ('',''),
                  'mailto': ('mailto:pyats-support-ext@%s','mailto'),
                  'setuptools': ('%s://setuptools.readthedocs.io/en/latest/setuptools.html#develop-deploy-the-project-source-in-development-mode','setuptools'),
                  'connection-pool': ("%ss://pubhub.devnetcloud.com/media/pyats/docs/connections/sharing.html#connection-pools","connection-pool"),
                  'lookupdecorator':('%ss://pubhub.devnetcloud.com/media/genie-abstraction/docs/lookup_decorator.html','lookupdecorator'),
                  'robot': ('%ss://pubhub.devnetcloud.com/media/genie-docs/docs/userguide/robot.html','robot'),
                  'robotframework': ('%s://robotframework.org/','robotframework'),
                  'triggers': ('%ss://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/triggers','triggers'),
                  'parsers': ('%ss://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/parsers','parsers'),
                  'verifications': ('%ss://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/verifications','verifications'),
                  'models': ('%ss://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/models','models'),
                  'lookupclass': ('%ss://pubhub.devnetcloud.com/media/genie-abstraction/docs/lookup_class.html','lookupclass'),
                  'abstract_topology':('%ss://pubhub.devnetcloud.com/media/genie-abstraction/docs/lookup_class.html#integration-with-topology','abstract_topology'),
                  'best': ('',''),
                  'testbed': ('%ss://pubhub.devnetcloud.com/media/pyats/docs/topology/index.html','testbed'),
                  'steps': ('%ss://pubhub.devnetcloud.com/media/pyats/docs/aetest/steps.html','steps'),
                  'easypy': ('%ss://pubhub.devnetcloud.com/media/pyats/docs/easypy/usages.html#standard-arguments','easypy'),
                  'aetest': ('%ss://pubhub.devnetcloud.com/media/pyats/docs/aetest/run.html#standard-arguments','aetest'),
                  'jobfile':('%ss://pubhub.devnetcloud.com/media/pyats/docs/easypy/jobfile.html','jobfile'),
                  'logic': ('%ss://pubhub.devnetcloud.com/media/pyats/docs/datastructures/logic.html','logic'),
                  'processors': ('%ss://pubhub.devnetcloud.com/media/pyats/docs/aetest/processors.html','processors'),
                  'ydk':('%ss://github.com/CiscoDevNet/ydk-gen/','ydk'),
                  'connection':('%ss://pubhub.devnetcloud.com/media/pyats/docs/connections/integration.html','connection'),
                  'unicon_recording':('%s://pubhub.devnetcloud.com/media/unicon/docs/playback/index.html#record','unicon_recording'),
                  'unicon_replay':('%s://pubhub.devnetcloud.com/media/unicon/docs/playback/index.html#replay','unicon_replay'),
                  'unicon_playback':('%s://pubhub.devnetcloud.com/media/unicon/docs/playback/index.html','unicon_playback'),
                  'pyats_topology': ('%ss://pubhub.devnetcloud.com/media/pyats/docs/topology/index.html','pyats_topology'),
                  'pyats_interface':('%ss://pubhub.devnetcloud.com/media/pyats/docs/topology/concept.html#interface-objects','pyats_interface'),
                  'pyats_link':('%ss://pubhub.devnetcloud.com/media/pyats/docs/topology/concept.html#link-objects','pyats_link'),
                  'pyats_device':('%ss://pubhub.devnetcloud.com/media/pyats/docs/topology/concept.html#device-objects','pyats_device'),
                  'pyats_gettingstarted':('%ss://pubhub.devnetcloud.com/media/pyats/docs/getting_started/index.html#installation','pyats_gettingstarted'),
                  'pyats_settestbed':('%ss://pubhub.devnetcloud.com/media/pyats/docs/getting_started/index.html#describe-your-testbed','pyats_settestbed'),
                  'pyats_secret_string': ('%s://pubhub.devnetcloud.com/media/pyats/docs/utilities/secret_strings.html#secret-strings','pyats_secret_string'),
                  'genietelemetry':('%ss://pubhub.devnetcloud.com/media/genie-telemetry/docs/index.html','genietelemetry'),
                  'genietrafficgen':('%ss://pubhub.devnetcloud.com/media/genie-trafficgen/docs/index.html','genietrafficgen'),
                  'subsections':('%ss://pubhub.devnetcloud.com/media/pyats/docs/aetest/structure.html#subsections','subsections'),
                  'filetransferutils_examples':('%ss://pubhub.devnetcloud.com/media/genie-filetransfer-utils/docs/introduction.html#example','filetransferutils_examples'),
                  'filetransferutils':('%ss://pubhub.devnetcloud.com/media/genie-filetransfer-utils/docs/introduction.html','filetransferutils'),
                  'geniewiki':('',''),
                  'pyatswiki':('',''),
                  'testcase':('%s://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/triggers','testcases'),
                  'virl':('%s://learningnetworkstore.cisco.com/virtual-internet-routing-lab-virl','virl'),
                  'windows':('%s://virl-dev-innovate.cisco.com/player.php','Windows'),
                  'mac':('%s://virl-dev-innovate.cisco.com/fusion.php','Mac'),
                  'vsphere':('%s://virl-dev-innovate.cisco.com/vs.web.php','vSphere'),
                  'virl_tutorials':('%s://virl-dev-innovate.cisco.com/tutorials.php','Virl Tutorials'),
                  'cisco_virl':('%s://www.youtube.com/channel/UC41WuzXlJCGY5qLsuZ8aHkQ','Cisco VIRL'),
                  'genielibsgitclone':('git@github.com:CiscoTestAutomation/genielibs',None),
                  'genieparsergitclone':('git@github.com:CiscoTestAutomation/genieparser',None),
                  'pyats_robot':('%s://pubhub.devnetcloud.com/media/pyats/docs/robot/index.html', 'pyats_robot'),
                  'devnet':('%ss://developer.cisco.com/site/pyats/', 'devnet'),
                  'internal_devnet':('', 'internal_devnet'),
                  'pyats_rollup':('%ss://pubhub.devnetcloud.com/media/pyats/docs/results/rollup.html','file transfer utils example'),
                  'pyats_find':('%ss://pubhub.devnetcloud.com/media/pyats/docs/utilities/helper_functions.html#find', 'pyats_find'),
                  'reserve':('%ss://github.com/CiscoDevNet/pyats-labs/blob/master/labs/intro-to-genie/1.md#prerequisites', 'reserve'),
                  'launch':('%ss://github.com/CiscoDevNet/pyats-labs/blob/master/labs/intro-to-genie/2.md#step-2-launch-genie-virl-simulation', 'launch'),
                  'pickle':('%ss://docs.python.org/3.5/library/pickle.html', 'pickle'),
                  'regex':('%ss://docs.python.org/3.5/library/re.html', 'regex'),
                  'ixiasupport':('%ss://support.ixiacom.com/support-overview/product-support/downloads-updates/versions/68', 'ixiasupport'),
                  'ixnetwork_pypi':('%ss://pypi.org/project/ixnetwork/', 'ixnetwork_pypi'),
                  'atsinstall':('', 'atsinstall'),
                  'atsc3':('', 'atsc3'),
                  'sdkchangelog':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/sdk-pkg/changelog/2018/%s.md', 'sdkchangelog'),
                  'parserchangelog':('https://github.com/CiscoTestAutomation/genieparser/blob/master/changelog/2018/%s.md', 'parserchangelog'),
                  'confchangelog':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/conf-pkg/changelog/2018/%s.md', 'confchangelog'),
                  'opschangelog':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/ops-pkg/changelog/2018/%s.md', 'opschangelog'),
                  'robotchangelog':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/robot-pkg/changelog/2018/%s.md', 'robotchangelog'),
                  'sdkchangelog19':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/sdk-pkg/changelog/2019/%s.md', 'sdkchangelog'),
                  'parserchangelog19':('https://github.com/CiscoTestAutomation/genieparser/blob/master/changelog/2019/%s.md', 'parserchangelog'),
                  'confchangelog19':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/conf-pkg/changelog/2019/%s.md', 'confchangelog'),
                  'opschangelog19':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/ops-pkg/changelog/2019/%s.md', 'opschangelog'),
                  'robotchangelog19':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/robot-pkg/changelog/2019/%s.md', 'robotchangelog'),
                  'sdkchangelog20':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/sdk-pkg/changelog/2020/%s.md', 'sdkchangelog'),
                  'parserchangelog20':('https://github.com/CiscoTestAutomation/genieparser/blob/master/changelog/2020/%s.md', 'parserchangelog'),
                  'cleanchangelog20':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/clean-pkg/changelog/2020/%s.md', 'cleanchangelog'),
                  'confchangelog20':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/conf-pkg/changelog/2020/%s.md', 'confchangelog'),
                  'opschangelog20':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/ops-pkg/changelog/2020/%s.md', 'opschangelog'),
                  'robotchangelog20':('https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/robot-pkg/changelog/2020/%s.md', 'robotchangelog'),
                  'trafficgenchangelog20':('https://github.com/CiscoTestAutomation/genietrafficgen/blob/master/docs/changelog/2020%s.rst', 'trafficgenchangelog'),
                  'genie_training_kata':('%ss://www.katacoda.com/jeaubin/scenarios/install', 'genie_training_kata'),
                  'genie_training_kata':('%ss://www.katacoda.com/jeaubin/scenarios/install', 'genie_training_kata'),
                  'genie_workshop':('%ss://github.com/CiscoTestAutomation/CL-DevNet-2595', 'genie_workshop'),
                  'pyats_genie_workshop':('%ss://github.com/RunSi/DEVWKS-2601', 'pyats_genie_workshop'),
                  'genie_command_line': ('%ss://pubhub.devnetcloud.com/media/genie-docs/docs/cli/index.html','genie_command_line'),
                  'genie_traffic_gen': ('%ss://pubhub.devnetcloud.com/media/genie-trafficgen/docs/index.html','genie_traffic_gen'),
                  'genie_bootcamp': ('',''),
                  'classtutorial': ('%s://docs.python.org/3/tutorial/classes.html', 'Class tutorial'),
                  'wikipedia': ('%s://en.wikipedia.org/wiki/Abstraction_(software_engineering)', 'Wikipedia'),
                  'dynamicallytyped': ('%s://en.wikipedia.org/wiki/Type_system#Dynamic_type_checking_and_runtime_type_information', 'dynamically typed'),
                  'ducktyping': ('%s://en.wikipedia.org/wiki/Duck_typing', 'duck typing'),
                  'inheritance': ('%s://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)', 'inheritance'),
                  'objectoriented': ('%s://en.wikipedia.org/wiki/Object-oriented_programming', 'object-oriented'),
                  'FactoryMethods': ('%s://en.wikipedia.org/wiki/Factory_(object-oriented_programming)', 'Factory Methods'),
                  'pythonmodules': ('%s://docs.python.org/3/tutorial/modules.html#packages', 'Python Modules'),
                  'pythonpackages': ('%s://docs.python.org/3/tutorial/modules.html', 'Python Packages'),
                  'pythonimportsystem': ('%s://docs.python.org/3/reference/import.html', 'Python Import System'),
                  'modulenamingconvention': ('%s://www.python.org/dev/peps/pep-0008/#package-and-module-names', 'module naming convention'),
                  'codereview': ('%ss://github.com/CiscoTestAutomation/genieparser/compare?expand=1', 'code review'),
                  'staticscope': ('%s://docs.python.org/3/whatsnew/2.1.html', 'static scope'),
                  'inheritancetutorial': ('%s://docs.python.org/2/tutorial/classes.html?highlight=inheritance', 'Inheritance Tutorial'),
                  'parsergenworkshop': ('%s://github.com/RunSi/DEVWKS-2601', 'parsergen workshop'),
                  'vod': ('', 'Vod'),
                  'communityforum': ('%ss://communities.cisco.com/community/developer/pyats', 'community forum'),
                  'blitz': ('%s://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writetrigger/writetrigger.html', 'blitz'),
                  'ListDict': ('%s://pubhub.devnetcloud.com/media/pyats/docs/datastructures/listdict.html', 'ListDict'),
                  }


# abstract
# internal_links = {'pyats': ('%s://wwwin-pyats.cisco.com', 'pyATS'),
#                   'devnet': ('%s://developer.cisco.com/', 'Cisco DevNet'),
#                   'mailto': ('mailto:asg-genie-support@%s','mailto'),
#                   'communityforum': ('%s://piestack.cisco.com', 'community forum'),
#                   'wikipedia': ('%s://en.wikipedia.org/wiki/Abstraction_(software_engineering)', 'Wikipedia'),
#                   'dynamicallytyped': ('%s://en.wikipedia.org/wiki/Type_system#Dynamic_type_checking_and_runtime_type_information', 'dynamically typed'),
#                   'ducktyping': ('%s://en.wikipedia.org/wiki/Duck_typing', 'duck typing'),
#                   'inheritance': ('%s://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)', 'inheritance'),
#                   'objectoriented': ('%s://en.wikipedia.org/wiki/Object-oriented_programming', 'object-oriented'),
#                   'FactoryMethods': ('%s://en.wikipedia.org/wiki/Factory_(object-oriented_programming)', 'Factory Methods'),
#                   'PythonModules': ('%s://docs.python.org/3/tutorial/modules.html#packages', 'Python Modules'),
#                   'PythonPackages': ('%s://docs.python.org/3/tutorial/modules.html', 'Python Packages'),
#                   'PythonImportSystem': ('%s://docs.python.org/3.4/reference/import.html', 'Python Import System'),
#                   'modulenamingconvention': ('%s://www.python.org/dev/peps/pep-0008/#package-and-module-names', 'module naming convention'),
#                   }

# external_links = {'pyats': ('%ss://developer.cisco.com/site/pyats/', 'pyATS'),
#                   'devnet': ('%ss://developer.cisco.com/', 'Cisco DevNet'),
#                   'mailto': ('mailto:pyats-support-ext@%s','mailto'),
#                   'communityforum': ('%ss://communities.cisco.com/community/developer/pyats', 'community forum'),
#                   'wikipedia': ('%s://en.wikipedia.org/wiki/Abstraction_(software_engineering)', 'Wikipedia'),
#                   'dynamicallytyped': ('%s://en.wikipedia.org/wiki/Type_system#Dynamic_type_checking_and_runtime_type_information', 'dynamically typed'),
#                   'ducktyping': ('%s://en.wikipedia.org/wiki/Duck_typing', 'duck typing'),
#                   'inheritance': ('%s://en.wikipedia.org/wiki/Inheritance_(object-oriented_programming)', 'inheritance'),
#                   'objectoriented': ('%s://en.wikipedia.org/wiki/Object-oriented_programming', 'object-oriented'),
#                   'FactoryMethods': ('%s://en.wikipedia.org/wiki/Factory_(object-oriented_programming)', 'Factory Methods'),
#                   'PythonModules': ('%s://docs.python.org/3/tutorial/modules.html#packages', 'Python Modules'),
#                   'PythonPackages': ('%s://docs.python.org/3/tutorial/modules.html', 'Python Packages'),
#                   'PythonImportSystem': ('%s://docs.python.org/3.4/reference/import.html', 'Python Import System'),
#                   'modulenamingconvention': ('%s://www.python.org/dev/peps/pep-0008/#package-and-module-names', 'module naming convention'),
#                   }

# metaparser
# internal_links = {'abstract': ('%s://wwwin-pyats.cisco.com/cisco-shared/abstract/html/', 'abstract'),
#                   'codereview': ('%s://bitbucket-eng-sjc1.cisco.com/bitbucket/projects/PYATS-PYPI/repos/genieparser/pull-requests?create', 'code review'),
#                   'pyats': ('%s://wwwin-pyats.cisco.com', 'pyATS'),
#                   'staticscope': ('%s://docs.python.org/3/whatsnew/2.1.html', 'static scope'),
#                   'devnet': ('%s://developer.cisco.com/', 'Cisco DevNet'),
#                   'mailto': ('mailto:asg-genie-support@%s','mailto'),
#                   'communityforum': ('%s://piestack.cisco.com', 'community forum'),
#                   'parsergen': ('%s://wwwin-pyats.cisco.com/cisco-shared/parsergen/latest/index.html', 'parsergen'),
#                   'classtutorial': ('%s://docs.python.org/3.4/tutorial/classes.html', 'Class tutorial'),
#                   'inheritancetutorial': ('%s://docs.python.org/2/tutorial/classes.html?highlight=inheritance', 'Inheritance Tutorial'),
#                   'parsers': ('%s://wwwin-pyats.cisco.com/cisco-shared/genie/latest/genie_libs/#/verifications', 'parsers'),
#                   'schemaengine': ('%s://wwwin-pyats.cisco.com/cisco-shared/metaparser/latest/advanced/schemaengine.html?highlight=schema', 'schema engine documentation'),
#                   }

# external_links = {'abstract': ('%ss://pubhub.devnetcloud.com/media/pyats-packages/docs/abstract/index.html', 'abstract'),
#                   'codereview': ('%ss://github.com/CiscoTestAutomation/genieparser/compare?expand=1', 'code review'),
#                   'pyats': ('%ss://developer.cisco.com/site/pyats/', 'pyATS'),
#                   'staticscope': ('%ss://docs.python.org/3/whatsnew/2.1.html', 'static scope'),
#                   'devnet': ('%ss://developer.cisco.com/', 'Cisco DevNet'),
#                   'mailto': ('mailto:pyats-support-ext@%s','mailto'),
#                   'communityforum': ('%ss://communities.cisco.com/community/developer/pyats', 'community forum'),
#                   'parsergen': ('%ss://pubhub.devnetcloud.com/media/pyats-packages/docs/parsergen/index.html', 'parsergen'),
#                   'classtutorial': ('%ss://docs.python.org/3.4/tutorial/classes.html', 'Class Tutorial'),
#                   'inheritancetutorial': ('%ss://docs.python.org/2/tutorial/classes.html?highlight=inheritance', 'Inheritance Tutorial'),
#                   'parsers': ('%ss://pubhub.devnetcloud.com/media/pyats-packages/docs/genie/genie_libs/#/verifications', 'parsers'),
#                   'schemaengine': ('%ss://pubhub.devnetcloud.com/media/pyats-packages/docs/metaparser/advanced/schemaengine.html?highlight=schema', 'schema engine documentation'),
#                   }

# parsergen
# internal_links = {'pyats': ('%s://wwwin-pyats.cisco.com', 'pyATS'),
#                   'devnet': ('%s://developer.cisco.com/', 'Cisco DevNet'),
#                   'mailto': ('mailto:asg-genie-support@%s','mailto'),
#                   'communityforum': ('%s://piestack.cisco.com', 'community forum'),
#                   'parsergenworkshop': ('%s://github.com/RunSi/DEVWKS-2601', 'parsergen workshop'),
#                   }

# external_links = {'pyats': ('%s://developer.cisco.com/site/pyats/', 'pyATS'),
#                   'devnet': ('%s://developer.cisco.com/', 'Cisco DevNet'),
#                   'mailto': ('mailto:pyats-support-ext@%s','mailto'),
#                   'communityforum': ('%ss://communities.cisco.com/community/developer/pyats', 'community forum'),
#                   'parsergenworkshop': ('%s://github.com/RunSi/DEVWKS-2601', 'parsergen workshop'),
#                   }

# predcore

# internal_links = {'mailto': ('mailto:asg-genie-support@%s','mailto'),
#                   'communityforum': ('%s://piestack.cisco.com', 'community forum'),
#                   'vod': ('%s://cisco.webex.com/ciscosales/ldr.php?RCID=b963a0319429876a8b332bf9b0962a1f', 'Vod'),
#                   }

# external_links = {'mailto': ('mailto:pyats-support-ext@%s','mailto'),
#                   'communityforum': ('%s:%s://communities.cisco.com/community/developer/pyats', 'community forum'),
#                   'vod': ('', 'Vod'),
#                   }
